# Generated by Django 4.1 on 2022-08-18 14:36
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_super_user(apps, schema_editor):
    Account = get_user_model()

    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_USER_NAME = os.environ.get('DJANGO_SU_USER_NAME')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    Account.objects.create_superuser(
        email=DJANGO_SU_EMAIL,
        user_name=DJANGO_SU_USER_NAME,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
