# Generated by Django 4.1 on 2022-08-19 11:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contents', models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('size', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(regex='(\\d+(,\\d+)?)x(\\d+(,\\d+)?)x(\\d+(,\\d+)?)')])),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parcels', models.ManyToManyField(blank=True, null=True, related_name='shelf_parcel', to='parcel_management_app.parcel')),
            ],
        ),
    ]
