# Generated by Django 4.1 on 2022-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelshelf',
            name='parcels',
            field=models.ManyToManyField(blank=True, related_name='shelf_parcel', to='parcel_management_app.parcel'),
        ),
    ]
