# Generated by Django 4.1 on 2022-08-19 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management_app', '0002_alter_parcelshelf_parcels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='size',
            field=models.CharField(blank=True, error_messages={'required': 'correct format: A,AxB,BxC,C'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='(\\d+(,\\d+)?)x(\\d+(,\\d+)?)x(\\d+(,\\d+)?)')]),
        ),
    ]
