# Generated by Django 4.1 on 2022-08-19 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management_app', '0003_alter_parcel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='size',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Correct value: A,AxB,BxC,C', regex='(\\d+(,\\d+)?)x(\\d+(,\\d+)?)x(\\d+(,\\d+)?)')]),
        ),
    ]
