# Generated by Django 4.1 on 2022-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management_app', '0004_alter_parcel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='code',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
