# Generated by Django 4.1 on 2022-08-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management_app', '0006_alter_parcel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
